const MONGODB_COLLECTION_ACTS = process.env.MONGODB_COLLECTION_ACTS;
const MONGODB_COLLECTION_GAMES = process.env.MONGODB_COLLECTION_GAMES;
const MONGODB_COLLECTION_STATS = process.env.MONGODB_COLLECTION_STATS;
const MONGODB_COLLECTION_USERS = process.env.MONGODB_COLLECTION_USERS;

export const getCollectionENV = () => {
  if (
    !MONGODB_COLLECTION_ACTS ||
    !MONGODB_COLLECTION_GAMES ||
    !MONGODB_COLLECTION_STATS ||
    !MONGODB_COLLECTION_USERS
  ) {
    console.error('Parthenon: Missing Necessary Environment Variables');
  }

  return {
    MONGODB_COLLECTION_ACTS,
    MONGODB_COLLECTION_GAMES,
    MONGODB_COLLECTION_STATS,
    MONGODB_COLLECTION_USERS,
  };
};
